### ISSUE TITLE
WARNING [bioservices:keggparser:119]

### ISSUE THREAD

**Issue by raven44099** [cokelaer/bioservices#203]
I just follow the request to report the warning here. I run a line from the tutorial ( https://bioservices.readthedocs.io/en/master/kegg_tutorial.html ), which is great by the way and I like bioservices.kegg already after running 5 lines. Wow!
The tutorials line is:
`k.get_pathway_by_gene("zap70", "hsa")`
The output:
```
WARNING [bioservices:keggparser:119]:  Found keyword SYMBOL, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (7535              CDS       T01001) into github.com/bioservices. Thanks T.C.
WARNING [bioservices:keggparser:119]:  Could not parse the entry CDS       T01001 correctly
WARNING [bioservices:keggparser:119]:  not enough values to unpack (expected 2, got 1)
Pfam  PK_Tyr_Ser-Thr Pkinase SH2 ABC1 Haspin_kinase Kdo
```

By the way, the github.com/bioservices is wrong, I think it should point to this issues-page.

**Comment by raven44099** [comment]
I do not request you answer all my issues, but I kindly want to note an error in the line:
`res = s.parse_kgml_pathway("hsa04660")`

<details><summary>Error</summary>
<p>

```
Traceback (most recent call last):

  File "/tmp/ipykernel_10118/2696537334.py", line 1, in <module>
    res = s.parse_kgml_pathway("hsa04660")

  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/bioservices/kegg.py", line 973, in parse_kgml_pathway
    res = self.easyXML(self.get(pathwayId, "kgml"))

  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/bioservices/services.py", line 211, in easyXML
    return xmltools.easyXML(res)

  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/bioservices/xmltools.py", line 86, in __init__
    self.prettify = self.soup.prettify

  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/bioservices/xmltools.py", line 98, in _get_soup
    self._soup = bs4.BeautifulSoup(self.data, "lxml")

  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/bs4/__init__.py", line 245, in __init__
    raise FeatureNotFound(

FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

</p>
</details>

**Comment by cokelaer** [comment]
@raven44099 thanks for reporting this issue.
Release 1.8.4 to appera soon on pypi will fix the warning
