### ISSUE TITLE
New error when using db2db:

### ISSUE THREAD

**Issue by babessell1** [cokelaer/bioservices#206]
Have used BioDbNet's db2db with no issue for a long time and I recently updated my docker to find this issue when using the arguments:

input_db = 'Ensembl Gene ID'
output_db = ['Gene Symbol', 'Gene ID', 'Chromosomal Location']
input_values = a list of ENSEMBL ID's 
TAXON = 9606

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bioservices/biodbnet.py", line 148, in db2db
    df.set_index("InputValue", inplace=True)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4727, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['InputValue'] are in the columns"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rnaseq_preprocess.py", line 280, in <module>
    main(sys.argv[1:])
  File "rnaseq_preprocess.py", line 273, in main
    handle_tissue_batch(tissue_names, mode, technique, form, taxon_id)
  File "rnaseq_preprocess.py", line 131, in handle_tissue_batch
    create_gene_info_file(tissue_name, count_matrix_file, form, taxon_id, gene_output_dir)
  File "rnaseq_preprocess.py", line 94, in create_gene_info_file
    gene_info = fetch_gene_info(genes, input_db=form, output_db=output_db, taxon_id=taxon_id)
  File "rnaseq_preprocess.py", line 49, in fetch_gene_info
    df_test = s.db2db(input_db, output_db, input_values[i:upper_range], taxon_id)
  File "/usr/local/lib/python3.8/dist-packages/bioservices/biodbnet.py", line 152, in db2db
    self.logging.error(err)
AttributeError: 'BioDBNet' object has no attribute 'logging'

Any help would be greatly appreciated!

**Comment by babessell1** [comment]
Never mind, I had accidentally made a type when I refactored causing an empty list to be queried. It is still true that there is a problem with the logging feature in bioDBNet if it has a chance to reach that exception.
