### ISSUE TITLE
Kegg parser module with non-supported attribute

### ISSUE THREAD

**Issue by EmanuelGoncalves** [cokelaer/bioservices#29]
Hi,

When parsing the some kegg modules a NotImplementedError was raised, see example below:

m = 'M00144'
s.parse(kegg_srv.get(p))

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-1c4e53a5473a>", line 1, in <module>
    dict([(p, s.parse(kegg_srv.get(p))) for p in kegg_pathways])
  File "/Library/Python/2.7/site-packages/bioservices/kegg.py", line 1254, in parse
    raise NotImplementedError("Entry %s not yet implemented" % dbentry)
NotImplementedError: Entry Complex   Module not yet implemented

Thanks.

Cheers,

**Comment by cokelaer** [comment]
This example works in the trunk. See also #30 issue comments
