### ISSUE TITLE
Problem with ncbiblast.py

### ISSUE THREAD

**Issue by shlicshlac** [cokelaer/bioservices#61]
I just ran the example code in the [docs page for NCBIblast](https://pythonhosted.org/bioservices/references.html#module-bioservices.ncbiblast) and I got this error:

```
>>> from bioservices import *
>>> s = NCBIblast(verbose=False)
INFO:root:Initialising NCBIblast service (REST)
>>> jobid = s.run(program="blastp", sequence=s._sequence_example,
...     stype="protein", database="uniprotkb", email="***@***.com")
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.ebi.ac.uk
>>> s.getResult(jobid, "out")
WARNING:root:waiting for the job to be finished. May take a while
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\..................\Anaconda3\lib\site-packages\bioservices\ncbiblast.py", line 382, in getResult
    self.wait(jobid, verbose=False)
TypeError: wait() got an unexpected keyword argument 'verbose'
```

Looking inside ncbiblast.py shows that the wait function definition only takes two parameters:
`def wait(self, jobId):`

**Comment by cokelaer** [comment]
Should be fixed in the master branch; Thanks for reporting this issue
